require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WirelessProvidersController do

  # This should return the minimal set of attributes required to create a valid
  # WirelessProvider. As you add validations to WirelessProvider, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WirelessProvidersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all wireless_providers as @wireless_providers" do
      wireless_provider = WirelessProvider.create! valid_attributes
      get :index, {}, valid_session
      assigns(:wireless_providers).should eq([wireless_provider])
    end
  end

  describe "GET show" do
    it "assigns the requested wireless_provider as @wireless_provider" do
      wireless_provider = WirelessProvider.create! valid_attributes
      get :show, {:id => wireless_provider.to_param}, valid_session
      assigns(:wireless_provider).should eq(wireless_provider)
    end
  end

  describe "GET new" do
    it "assigns a new wireless_provider as @wireless_provider" do
      get :new, {}, valid_session
      assigns(:wireless_provider).should be_a_new(WirelessProvider)
    end
  end

  describe "GET edit" do
    it "assigns the requested wireless_provider as @wireless_provider" do
      wireless_provider = WirelessProvider.create! valid_attributes
      get :edit, {:id => wireless_provider.to_param}, valid_session
      assigns(:wireless_provider).should eq(wireless_provider)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WirelessProvider" do
        expect {
          post :create, {:wireless_provider => valid_attributes}, valid_session
        }.to change(WirelessProvider, :count).by(1)
      end

      it "assigns a newly created wireless_provider as @wireless_provider" do
        post :create, {:wireless_provider => valid_attributes}, valid_session
        assigns(:wireless_provider).should be_a(WirelessProvider)
        assigns(:wireless_provider).should be_persisted
      end

      it "redirects to the created wireless_provider" do
        post :create, {:wireless_provider => valid_attributes}, valid_session
        response.should redirect_to(WirelessProvider.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wireless_provider as @wireless_provider" do
        # Trigger the behavior that occurs when invalid params are submitted
        WirelessProvider.any_instance.stub(:save).and_return(false)
        post :create, {:wireless_provider => {}}, valid_session
        assigns(:wireless_provider).should be_a_new(WirelessProvider)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WirelessProvider.any_instance.stub(:save).and_return(false)
        post :create, {:wireless_provider => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wireless_provider" do
        wireless_provider = WirelessProvider.create! valid_attributes
        # Assuming there are no other wireless_providers in the database, this
        # specifies that the WirelessProvider created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WirelessProvider.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => wireless_provider.to_param, :wireless_provider => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested wireless_provider as @wireless_provider" do
        wireless_provider = WirelessProvider.create! valid_attributes
        put :update, {:id => wireless_provider.to_param, :wireless_provider => valid_attributes}, valid_session
        assigns(:wireless_provider).should eq(wireless_provider)
      end

      it "redirects to the wireless_provider" do
        wireless_provider = WirelessProvider.create! valid_attributes
        put :update, {:id => wireless_provider.to_param, :wireless_provider => valid_attributes}, valid_session
        response.should redirect_to(wireless_provider)
      end
    end

    describe "with invalid params" do
      it "assigns the wireless_provider as @wireless_provider" do
        wireless_provider = WirelessProvider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WirelessProvider.any_instance.stub(:save).and_return(false)
        put :update, {:id => wireless_provider.to_param, :wireless_provider => {}}, valid_session
        assigns(:wireless_provider).should eq(wireless_provider)
      end

      it "re-renders the 'edit' template" do
        wireless_provider = WirelessProvider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WirelessProvider.any_instance.stub(:save).and_return(false)
        put :update, {:id => wireless_provider.to_param, :wireless_provider => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wireless_provider" do
      wireless_provider = WirelessProvider.create! valid_attributes
      expect {
        delete :destroy, {:id => wireless_provider.to_param}, valid_session
      }.to change(WirelessProvider, :count).by(-1)
    end

    it "redirects to the wireless_providers list" do
      wireless_provider = WirelessProvider.create! valid_attributes
      delete :destroy, {:id => wireless_provider.to_param}, valid_session
      response.should redirect_to(wireless_providers_url)
    end
  end

end
